Fix equipments support and expedition requirements to 2022.04
poooi/poi-plugin-ezexped pull request #43
Opened 2022-04-06 12:20 UTC by OniJAM

修复了舰队菜单里大发系装备图标的显示
更新远征成功条件，来源: https://wikiwiki.jp/kancolle/%E9%81%A0%E5%BE%81
https://bbs.nga.cn/read.php?tid=21866416
ps. 我没有使用 escortSpecialFleetCompos，因为里面的成功条件都可以和海域基础成功条件合并从而更简洁

2022-04-06 13:59 UTC, OniJAM commented
新增大成功率计算支持（通常型、桶型、旗舰lv型）替换原有提示

2022-04-11 05:18 UTC, Javran commented
版本號不要動, 其他沒問題.

2022-04-11 05:20 UTC, Javran requested changes
README.md 和 package.json裏的版本號不要改(README.md裏換成 `### Pending` 之類的). 我習慣publish的時候統一更新.

2022-04-11 08:26 UTC, merged

2022-04-11 08:26 UTC, Javran commented
Thanks!

2022-04-13 05:50 UTC, Javran commented on ui/requirement-viewer/ereq-list-group-item/gs-rate-drum-item.es
> +  props.result.sat = GSRateDrumCheck(props) >= 100
In hindsight I should have took a closer look on this - have you actually tested that this is working? Why the F are you setting props from UI?